import type { Archetype } from '@/types/assessment';

export const ARCHETYPES: Archetype[] = [
  // ── 01: The Unstructured Creative ──────────────────────────────
  {
    id: 'unstructured_creative',
    name: 'The Unstructured Creative',
    description: 'Early-stage creative with no formal business entity. Income under $150K. Needs infrastructure foundations before anything else.',
    stage_range: [1, 1.5],
    creative_modes: ['maker', 'service', 'hybrid', 'performer', 'builder', 'transition'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Form your business entity',
        what: 'Register an LLC in your state. If income exceeds $80K, discuss S-Corp election with a CPA before filing.',
        why: "An LLC is the container for everything — contracts, equity, tax efficiency, liability protection. You can't hold equity or sign business agreements without one.",
        how: 'LegalZoom, ZenBusiness, or Tailor Brands for filing. In Sequence lists creative-industry-experienced attorneys for complex situations.',
        timeline: '2 weeks',
        done_signal: 'You have an EIN number and a filed LLC.',
        providers: [
          { name: 'LegalZoom', url: 'https://www.legalzoom.com', type: 'platform' },
          { name: 'ZenBusiness', url: 'https://www.zenbusiness.com', type: 'platform' },
          { name: 'Tailor Brands', url: 'https://www.tailorbrands.com', type: 'platform' },
        ],
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Separate your business finances',
        what: "Open a business checking account and business credit card in your entity's name. Route all creative income through it.",
        why: 'Co-mingling funds is the #1 way creatives lose liability protection and overpay taxes. Clean separation = real business.',
        how: 'Mercury, Relay, or Novo for business checking. Any major issuer for business credit.',
        timeline: '1 week after Action 1',
        done_signal: 'All new payments deposit to business account. All business expenses go on business card.',
        providers: [
          { name: 'Mercury', url: 'https://mercury.com', type: 'platform' },
          { name: 'Relay', url: 'https://relayfi.com', type: 'platform' },
          { name: 'Novo', url: 'https://www.novo.co', type: 'platform' },
        ],
      },
      {
        order: 3,
        type: 'positioning',
        title: 'Get proper agreements in place',
        what: "Adopt or create a standard agreement for your creative work — whether that's client contracts, gallery agreements, licensing terms, collaboration agreements, or commission contracts. At minimum: scope, compensation, timeline, IP ownership, and termination terms.",
        why: "Agreements aren't just protection — they're positioning. And the IP clause is critical: understanding what you own vs. what you give away is the foundation of everything that follows.",
        how: 'In Sequence library includes agreement templates by discipline. For custom needs, consult with an attorney.',
        timeline: '2-3 weeks',
        done_signal: "You've used a proper agreement on your next engagement.",
        ai_assist: {
          prompt_template: 'Help me draft a [discipline] agreement for [situation] that protects my IP rights',
          context_keys: ['discipline', 'creative_mode', 'ip_ownership_answer'],
        },
      },
    ],
    structures: [1, 2],
    case_studies: [],
  },

  // ── 02: The Established Practitioner Ready to Transition ──────────
  {
    id: 'established_practitioner',
    name: 'The Established Practitioner Ready to Transition',
    description: 'Good income ($150K-$300K), infrastructure exists, but all income from execution/fees. Ready to price judgment separately.',
    stage_range: [1.5, 2.5],
    creative_modes: ['service', 'hybrid'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Identify your judgment-ready relationship',
        what: "Review your current clients or collaborators. Find the ONE who most often asks for your perspective on direction, not just your production. This is the relationship where your judgment is already valued — just not priced.",
        why: "You're already delivering Stage 2 value for Stage 1 compensation. This isn't about creating something new — it's about recognizing and restructuring what exists.",
        how: 'Filter: who would engage you even if someone else handled production? That\'s the one.',
        timeline: '1 week to identify, 2 weeks to schedule a conversation',
        done_signal: "You've identified the relationship and scheduled a meeting to discuss restructuring.",
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Draft a restructured engagement proposal',
        what: 'Create a proposal for a strategic/advisory engagement with that relationship. Scope: regular strategic guidance, creative direction, brand or product oversight. Pricing: value-based, not hourly.',
        why: 'The first advisory engagement changes your trajectory. It proves a market exists for your judgment separate from your hands.',
        how: 'The In Sequence AI assistant can help you draft this. It will use your assessment data, discipline context, and the relevant deal structure templates (Structure #4) to generate a starting point you can customize.',
        timeline: '2-3 weeks to draft, 3-4 weeks to present',
        done_signal: "You've presented the proposal. (The act of proposing matters more than the initial outcome.)",
        ai_assist: {
          prompt_template: 'Help me draft an advisory/strategic engagement proposal for [describe relationship and context]',
          context_keys: ['discipline', 'income_range', 'what_they_pay_for', 'demand_level'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Audit your unmonetized IP and judgment',
        what: "Make a simple inventory of (a) anything you've created that you own or could own, and (b) strategic judgment you've given away for free inside execution projects. This isn't about immediately monetizing — it's about seeing what you have.",
        why: "Most creatives at this stage are sitting on unrecognized assets — frameworks, IP, relationships with equity potential. You can't restructure what you can't see.",
        how: "Spreadsheet: What I Created | Who Owns It | Could I Retain/License It | Strategic Advice I Gave Free.",
        timeline: "2-3 weeks (doesn't need to be exhaustive — 80% is enough)",
        done_signal: 'You have a written inventory.',
      },
    ],
    structures: [3, 4],
    case_studies: [],
  },

  // ── 03: The Maker Without Structure ──────────────────────────────
  {
    id: 'maker_without_structure',
    name: 'The Maker Without Structure',
    description: 'Strong creative reputation, minimal business infrastructure. Often Stage 1 income but Stage 2-3 cultural influence.',
    stage_range: [1, 3],
    creative_modes: ['maker', 'performer'],
    required_flags: ['talent_without_structure'],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Get one strategic conversation',
        what: "Before forming entities or restructuring anything, talk to ONE person who can see your full situation — a business manager, creative-industry attorney, or strategic advisor. Not an agent (who takes a percentage) but someone who helps you BUILD infrastructure.",
        why: "The pure-creator archetype often doesn't want to learn business. That's fine. But you need someone who translates between creative vision and structural reality. The cost of doing nothing is real.",
        how: "In Sequence offers a free 30-minute advisory call for exactly this. We help identify whether you need a business manager, attorney, accountant, or some combination — and provide referrals.",
        timeline: 'Book within 1 week',
        done_signal: "You've had the conversation and have a clear next step.",
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Audit who owns what',
        what: "Create a simple inventory of your work from the last 3-5 years. For each piece: who owns the rights? Is there a contract? Is there revenue you're not capturing? Are there assets being used without compensation?",
        why: 'Most makers have significant IP assets they\'ve given away through default. This audit often reveals recoverable rights and patterns that need to stop.',
        how: 'Simple list: Work | Year | Who Owns It | Written Agreement? | Revenue? | Am I Getting Paid?',
        timeline: '2-3 weeks',
        done_signal: 'Written inventory exists.',
        ai_assist: {
          prompt_template: "Help me think through my IP ownership situation as a [discipline] — here's what I know about my catalog and deals",
          context_keys: ['discipline', 'ip_ownership_answer', 'industry_specific_answers'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Protect the next deal',
        what: 'For your NEXT project, commission, collaboration, or release — pause before committing and ensure written terms exist that protect your rights. If the default is work-for-hire or full rights transfer, negotiate for at minimum: licensing (not assignment), credit, and portfolio/promotional rights.',
        why: "You can't fix past deals, but you can stop the pattern. One well-structured agreement creates a template for everything after.",
        how: 'In Sequence library includes discipline-specific agreement frameworks. For music: Structure #25-26 (royalties). For film: Structure #25 (profit participation). For art: Structure #27-28 (licensing). For publishing: Structure #29-30 (rights reversion, subsidiary rights).',
        timeline: 'Apply to your literally next engagement',
        done_signal: 'Signed agreement with terms that protect your interests before work begins.',
      },
    ],
    structures: [25, 26, 27, 28, 29, 30],
    case_studies: [],
  },

  // ── 04: The Platform Builder ──────────────────────────────────────
  {
    id: 'platform_builder',
    name: 'The Platform Builder',
    description: 'Stage 2-3, successful core business. Wants to build holding company / multi-venture structure.',
    stage_range: [2, 3.5],
    creative_modes: ['builder', 'hybrid', 'service'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Design your entity architecture',
        what: 'Map the entity structure that supports your vision. Typically: a parent LLC (holding company) owning subsidiary LLCs for distinct business lines. Identify which entities exist and which need to be created.',
        why: 'Running multiple ventures through one entity is a liability, tax, and operational problem. The holding company structure creates clean separation, optimization, and the ability to sell, partner, or attract investment into specific entities.',
        how: 'Initial sketch on paper, then validate with a creative-industry attorney. This is NOT DIY. In Sequence provides attorney referrals who understand this architecture.',
        timeline: 'Entity map in 2 weeks. Attorney meeting within 4 weeks.',
        done_signal: 'Documented entity structure diagram and scheduled attorney consultation.',
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Level up your financial team',
        what: 'Engage a CPA who specializes in creative industries and multi-entity structures. If you have a generalist, assess whether they can handle the complexity you\'re building.',
        why: "A generalist CPA costs $20K-$100K+ annually in missed strategies. Creative-industry specialists understand project-based income, IP valuation, equity compensation, and multi-entity optimization.",
        how: 'In Sequence provides vetted referrals. Key question: "Do you work with other creatives who have holding company structures?"',
        timeline: 'First meeting within 3 weeks',
        done_signal: 'Engaged or scheduled with a creative-industry CPA.',
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Prepare your first formal equity term sheet',
        what: 'For your next collaboration where equity or ownership makes sense, create a proper term sheet BEFORE the conversation. Include: equity percentage, vesting, role definition, exit provisions, information rights, anti-dilution.',
        why: "Moving from \"let's figure it out\" to \"here are my proposed terms\" transforms you from hopeful participant to serious partner.",
        how: 'The In Sequence AI assistant can draft this with you using your context and the deal structure templates (Structures #17-21).',
        timeline: 'Identify opportunity within 2 weeks. Draft within 4 weeks.',
        done_signal: 'Written term sheet ready for your next equity conversation.',
        ai_assist: {
          prompt_template: 'Help me draft an equity term sheet for [describe opportunity]. I want to propose [general idea of terms].',
          context_keys: ['discipline', 'income_range', 'equity_positions', 'demand_level'],
        },
      },
    ],
    structures: [5, 9, 12, 14, 17, 18, 19, 20, 21],
    case_studies: [],
  },

  // ── 05: The Creative with Untapped Catalog ────────────────────────
  {
    id: 'untapped_catalog',
    name: 'The Creative with Untapped Catalog',
    description: 'Owns work or catalog but isn\'t generating ongoing revenue from it. Stage varies widely (1-3).',
    stage_range: [1, 3],
    creative_modes: ['maker', 'performer', 'hybrid'],
    required_flags: ['ip_not_monetized'],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Catalog your catalog',
        what: 'Create a comprehensive inventory of every piece of IP you own — music, art, writing, designs, photography, video, frameworks, tools. For each: current monetization status, licensing potential, and whether rights documentation exists.',
        why: "You can't monetize what you can't see. Most creatives with catalogs are leaving money on the table because they've never systematically assessed what they have and what it could generate.",
        how: 'Spreadsheet: Work Title | Medium | Year | Rights Status | Current Revenue | Licensing Potential (high/medium/low) | Notes.',
        timeline: '2-4 weeks (comprehensive, not perfect)',
        done_signal: 'Complete catalog inventory exists as a document.',
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Identify your highest-value licensing opportunity',
        what: 'From your inventory, identify the ONE piece or collection with the highest commercial licensing potential. Consider: Is there demand? Could this be licensed for merchandise, sync, print, digital use, education, or other applications?',
        why: 'One well-structured licensing deal can generate more recurring revenue than months of new production. And it creates a template for the rest of your catalog.',
        how: 'In Sequence Structures #27 (Non-Exclusive Licensing), #28 (Exclusive Licensing), #31 (Territory/Media Rights Splitting).',
        timeline: '2 weeks after catalog is complete',
        done_signal: "You've identified the opportunity and can describe the licensing structure in one paragraph.",
        ai_assist: {
          prompt_template: 'Help me evaluate the licensing potential of [describe work/catalog] and draft an initial licensing proposal',
          context_keys: ['discipline', 'ip_ownership_answer', 'catalog_inventory'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Make one licensing deal',
        what: 'Approach one potential licensee with a concrete proposal. Could be a brand, publisher, platform, sync agent, or retailer. Specific terms, specific timeline, specific rights granted (not all rights — specific, limited rights).',
        why: 'One deal proves the model. It generates evidence that your catalog has commercial value, which makes every subsequent deal easier.',
        how: 'Attorney review recommended for first licensing agreement. In Sequence provides referrals.',
        timeline: '4-6 weeks',
        done_signal: 'Signed licensing agreement with defined terms and payment schedule.',
      },
    ],
    structures: [27, 28, 31],
    case_studies: [],
  },

  // ── 06: The High-Earner Without Ownership ────────────────────────
  {
    id: 'high_earner_no_ownership',
    name: 'The High-Earner Without Ownership',
    description: 'Stage 2 (high-end) to 3. Significant income but no ownership positions. Structural gaps costing real money.',
    stage_range: [2, 3.5],
    creative_modes: ['maker', 'service', 'hybrid', 'performer', 'builder', 'transition'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Fix the structural gap',
        what: 'If sole prop or basic LLC earning $250K+, address entity structure and tax optimization immediately. Meet with a creative-industry CPA about S-Corp election, entity restructuring, and tax strategy.',
        why: 'At your income level, structural misalignment costs $15K-$50K+ annually in tax inefficiency alone — plus you lack the entity structure to hold equity if an opportunity arises.',
        how: 'In Sequence referrals to creative-industry CPAs and attorneys.',
        timeline: 'Consultation within 2 weeks. Implementation within 6 weeks.',
        done_signal: 'Tax-optimized entity structure in place.',
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Convert one relationship to ownership',
        what: "Identify your longest-standing, highest-trust professional relationship where you've contributed significant value. Propose restructuring the engagement to include equity, profit participation, or revenue share alongside (or instead of) fees.",
        why: "You have relationships where you've generated enormous value and captured none of the ownership. One conversion changes how you think about every relationship that follows.",
        how: 'In Sequence Structures #3 (Project Equity), #17 (Equity-for-Services), #24 (Revenue Share Partnership). The AI assistant can help you draft the proposal and model the terms.',
        timeline: 'Identify within 1 week. Draft proposal within 3 weeks. Conversation within 5 weeks.',
        done_signal: "You've had the ownership conversation with one key relationship.",
        ai_assist: {
          prompt_template: 'Help me draft an equity/ownership proposal for [relationship description]. Current engagement is [describe]. I want to propose [general direction].',
          context_keys: ['discipline', 'income_range', 'income_structure', 'what_they_pay_for', 'demand_level'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Start tracking your value creation',
        what: "For the next 90 days, document the value you create in every significant engagement. Not just deliverables — business outcomes, revenue generated, opportunities created, decisions influenced.",
        why: "Ownership conversations require evidence. When you can say \"my direction on your brand contributed to X% revenue growth,\" you're not asking for equity — you're demonstrating why it's appropriate.",
        how: 'Simple log: Engagement | What I Did | Business Impact (estimated) | Date.',
        timeline: 'Start immediately, review at 90 days',
        done_signal: '90-day value creation log exists and can be referenced in future negotiations.',
      },
    ],
    structures: [3, 17, 24],
    case_studies: [],
  },
];

/** Look up an archetype by ID */
export function getArchetypeById(id: string): Archetype | undefined {
  return ARCHETYPES.find(a => a.id === id);
}
