import type { Archetype } from '@/types/assessment';

export const ARCHETYPES: Archetype[] = [
  // ── 01: The Unstructured Creative ──────────────────────────────
  {
    id: 'unstructured_creative',
    name: 'The Unstructured Creative',
    description: 'Early-stage creative with no formal business entity. Income under $150K. Needs infrastructure foundations before anything else.',
    stage_range: [1, 1.5],
    creative_modes: ['maker', 'service', 'hybrid', 'performer', 'builder', 'transition'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Form your business entity',
        what: 'Register an LLC in your state. If income exceeds $80K, discuss S-Corp election with a CPA before filing.',
        why: "An LLC is the container for everything — contracts, equity, tax efficiency, liability protection. You can't hold equity or sign business agreements without one.",
        how: 'LegalZoom, ZenBusiness, or Tailor Brands for filing. In Sequence lists creative-industry-experienced attorneys for complex situations.',
        timeline: '2 weeks',
        done_signal: 'You have an EIN number and a filed LLC.',
        providers: [
          { name: 'LegalZoom', url: 'https://www.legalzoom.com', type: 'platform' },
          { name: 'ZenBusiness', url: 'https://www.zenbusiness.com', type: 'platform' },
          { name: 'Tailor Brands', url: 'https://www.tailorbrands.com', type: 'platform' },
        ],
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Separate your business finances',
        what: "Open a business checking account and business credit card in your entity's name. Route all creative income through it.",
        why: 'Co-mingling funds is the #1 way creatives lose liability protection and overpay taxes. Clean separation = real business.',
        how: 'Mercury, Relay, or Novo for business checking. Any major issuer for business credit.',
        timeline: '1 week after Action 1',
        done_signal: 'All new payments deposit to business account. All business expenses go on business card.',
        providers: [
          { name: 'Mercury', url: 'https://mercury.com', type: 'platform' },
          { name: 'Relay', url: 'https://relayfi.com', type: 'platform' },
          { name: 'Novo', url: 'https://www.novo.co', type: 'platform' },
        ],
      },
      {
        order: 3,
        type: 'positioning',
        title: 'Get proper agreements in place',
        what: "Adopt or create a standard agreement for your creative work — whether that's client contracts, gallery agreements, licensing terms, collaboration agreements, or commission contracts. At minimum: scope, compensation, timeline, IP ownership, and termination terms.",
        why: "Agreements aren't just protection — they're positioning. And the IP clause is critical: understanding what you own vs. what you give away is the foundation of everything that follows.",
        how: 'In Sequence library includes agreement templates by discipline. For custom needs, consult with an attorney.',
        timeline: '2-3 weeks',
        done_signal: "You've used a proper agreement on your next engagement.",
        ai_assist: {
          prompt_template: 'Help me draft a [discipline] agreement for [situation] that protects my IP rights',
          context_keys: ['discipline', 'creative_mode', 'ip_ownership_answer'],
        },
      },
    ],
    structures: [1, 2],
    case_studies: [],
  },

  // ── 02: The Established Practitioner Ready to Transition ──────────
  {
    id: 'established_practitioner',
    name: 'The Established Practitioner Ready to Transition',
    description: 'Good income ($150K-$300K), infrastructure exists, but all income from execution/fees. Ready to price judgment separately.',
    stage_range: [1.5, 2.5],
    creative_modes: ['service', 'hybrid'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Identify your judgment-ready relationship',
        what: "Review your current clients or collaborators. Find the ONE who most often asks for your perspective on direction, not just your production. This is the relationship where your judgment is already valued — just not priced.",
        why: "You're already delivering Stage 2 value for Stage 1 compensation. This isn't about creating something new — it's about recognizing and restructuring what exists.",
        how: 'Filter: who would engage you even if someone else handled production? That\'s the one.',
        timeline: '1 week to identify, 2 weeks to schedule a conversation',
        done_signal: "You've identified the relationship and scheduled a meeting to discuss restructuring.",
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Draft a restructured engagement proposal',
        what: 'Create a proposal for a strategic/advisory engagement with that relationship. Scope: regular strategic guidance, creative direction, brand or product oversight. Pricing: value-based, not hourly.',
        why: 'The first advisory engagement changes your trajectory. It proves a market exists for your judgment separate from your hands.',
        how: 'The In Sequence AI assistant can help you draft this. It will use your assessment data, discipline context, and the relevant deal structure templates (Structure #4) to generate a starting point you can customize.',
        timeline: '2-3 weeks to draft, 3-4 weeks to present',
        done_signal: "You've presented the proposal. (The act of proposing matters more than the initial outcome.)",
        ai_assist: {
          prompt_template: 'Help me draft an advisory/strategic engagement proposal for [describe relationship and context]',
          context_keys: ['discipline', 'income_range', 'what_they_pay_for', 'demand_level'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Audit your unmonetized IP and judgment',
        what: "Make a simple inventory of (a) anything you've created that you own or could own, and (b) strategic judgment you've given away for free inside execution projects. This isn't about immediately monetizing — it's about seeing what you have.",
        why: "Most creatives at this stage are sitting on unrecognized assets — frameworks, IP, relationships with equity potential. You can't restructure what you can't see.",
        how: "Spreadsheet: What I Created | Who Owns It | Could I Retain/License It | Strategic Advice I Gave Free.",
        timeline: "2-3 weeks (doesn't need to be exhaustive — 80% is enough)",
        done_signal: 'You have a written inventory.',
      },
    ],
    structures: [3, 4],
    case_studies: [],
  },

  // ── 03: The Maker Without Structure ──────────────────────────────
  {
    id: 'maker_without_structure',
    name: 'The Maker Without Structure',
    description: 'Strong creative reputation, minimal business infrastructure. Often Stage 1 income but Stage 2-3 cultural influence.',
    stage_range: [1, 3],
    creative_modes: ['maker', 'performer'],
    required_flags: ['talent_without_structure'],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Get one strategic conversation',
        what: "Before forming entities or restructuring anything, talk to ONE person who can see your full situation — a business manager, creative-industry attorney, or strategic advisor. Not an agent (who takes a percentage) but someone who helps you BUILD infrastructure.",
        why: "The pure-creator archetype often doesn't want to learn business. That's fine. But you need someone who translates between creative vision and structural reality. The cost of doing nothing is real.",
        how: "In Sequence offers a free 30-minute advisory call for exactly this. We help identify whether you need a business manager, attorney, accountant, or some combination — and provide referrals.",
        timeline: 'Book within 1 week',
        done_signal: "You've had the conversation and have a clear next step.",
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Audit who owns what',
        what: "Create a simple inventory of your work from the last 3-5 years. For each piece: who owns the rights? Is there a contract? Is there revenue you're not capturing? Are there assets being used without compensation?",
        why: 'Most makers have significant IP assets they\'ve given away through default. This audit often reveals recoverable rights and patterns that need to stop.',
        how: 'Simple list: Work | Year | Who Owns It | Written Agreement? | Revenue? | Am I Getting Paid?',
        timeline: '2-3 weeks',
        done_signal: 'Written inventory exists.',
        ai_assist: {
          prompt_template: "Help me think through my IP ownership situation as a [discipline] — here's what I know about my catalog and deals",
          context_keys: ['discipline', 'ip_ownership_answer', 'industry_specific_answers'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Protect the next deal',
        what: 'For your NEXT project, commission, collaboration, or release — pause before committing and ensure written terms exist that protect your rights. If the default is work-for-hire or full rights transfer, negotiate for at minimum: licensing (not assignment), credit, and portfolio/promotional rights.',
        why: "You can't fix past deals, but you can stop the pattern. One well-structured agreement creates a template for everything after.",
        how: 'In Sequence library includes discipline-specific agreement frameworks. For music: Structure #25-26 (royalties). For film: Structure #25 (profit participation). For art: Structure #27-28 (licensing). For publishing: Structure #29-30 (rights reversion, subsidiary rights).',
        timeline: 'Apply to your literally next engagement',
        done_signal: 'Signed agreement with terms that protect your interests before work begins.',
      },
    ],
    structures: [25, 26, 27, 28, 29, 30],
    case_studies: [],
  },

  // ── 04: The Platform Builder ──────────────────────────────────────
  {
    id: 'platform_builder',
    name: 'The Platform Builder',
    description: 'Stage 2-3, successful core business. Wants to build holding company / multi-venture structure.',
    stage_range: [2, 3.5],
    creative_modes: ['builder', 'hybrid', 'service'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Design your entity architecture',
        what: 'Map the entity structure that supports your vision. Typically: a parent LLC (holding company) owning subsidiary LLCs for distinct business lines. Identify which entities exist and which need to be created.',
        why: 'Running multiple ventures through one entity is a liability, tax, and operational problem. The holding company structure creates clean separation, optimization, and the ability to sell, partner, or attract investment into specific entities.',
        how: 'Initial sketch on paper, then validate with a creative-industry attorney. This is NOT DIY. In Sequence provides attorney referrals who understand this architecture.',
        timeline: 'Entity map in 2 weeks. Attorney meeting within 4 weeks.',
        done_signal: 'Documented entity structure diagram and scheduled attorney consultation.',
      },
      {
        order: 2,
        type: 'foundation',
        title: 'Level up your financial team',
        what: 'Engage a CPA who specializes in creative industries and multi-entity structures. If you have a generalist, assess whether they can handle the complexity you\'re building.',
        why: "A generalist CPA costs $20K-$100K+ annually in missed strategies. Creative-industry specialists understand project-based income, IP valuation, equity compensation, and multi-entity optimization.",
        how: 'In Sequence provides vetted referrals. Key question: "Do you work with other creatives who have holding company structures?"',
        timeline: 'First meeting within 3 weeks',
        done_signal: 'Engaged or scheduled with a creative-industry CPA.',
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Prepare your first formal equity term sheet',
        what: 'For your next collaboration where equity or ownership makes sense, create a proper term sheet BEFORE the conversation. Include: equity percentage, vesting, role definition, exit provisions, information rights, anti-dilution.',
        why: "Moving from \"let's figure it out\" to \"here are my proposed terms\" transforms you from hopeful participant to serious partner.",
        how: 'The In Sequence AI assistant can draft this with you using your context and the deal structure templates (Structures #17-21).',
        timeline: 'Identify opportunity within 2 weeks. Draft within 4 weeks.',
        done_signal: 'Written term sheet ready for your next equity conversation.',
        ai_assist: {
          prompt_template: 'Help me draft an equity term sheet for [describe opportunity]. I want to propose [general idea of terms].',
          context_keys: ['discipline', 'income_range', 'equity_positions', 'demand_level'],
        },
      },
    ],
    structures: [5, 9, 12, 14, 17, 18, 19, 20, 21],
    case_studies: [],
  },

  // ── 05: The Creative with Untapped Catalog ────────────────────────
  {
    id: 'untapped_catalog',
    name: 'The Creative with Untapped Catalog',
    description: 'Owns work or catalog but isn\'t generating ongoing revenue from it. Stage varies widely (1-3).',
    stage_range: [1, 3],
    creative_modes: ['maker', 'performer', 'hybrid'],
    required_flags: ['ip_not_monetized'],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Catalog your catalog',
        what: 'Create a comprehensive inventory of every piece of IP you own — music, art, writing, designs, photography, video, frameworks, tools. For each: current monetization status, licensing potential, and whether rights documentation exists.',
        why: "You can't monetize what you can't see. Most creatives with catalogs are leaving money on the table because they've never systematically assessed what they have and what it could generate.",
        how: 'Spreadsheet: Work Title | Medium | Year | Rights Status | Current Revenue | Licensing Potential (high/medium/low) | Notes.',
        timeline: '2-4 weeks (comprehensive, not perfect)',
        done_signal: 'Complete catalog inventory exists as a document.',
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Identify your highest-value licensing opportunity',
        what: 'From your inventory, identify the ONE piece or collection with the highest commercial licensing potential. Consider: Is there demand? Could this be licensed for merchandise, sync, print, digital use, education, or other applications?',
        why: 'One well-structured licensing deal can generate more recurring revenue than months of new production. And it creates a template for the rest of your catalog.',
        how: 'In Sequence Structures #27 (Non-Exclusive Licensing), #28 (Exclusive Licensing), #31 (Territory/Media Rights Splitting).',
        timeline: '2 weeks after catalog is complete',
        done_signal: "You've identified the opportunity and can describe the licensing structure in one paragraph.",
        ai_assist: {
          prompt_template: 'Help me evaluate the licensing potential of [describe work/catalog] and draft an initial licensing proposal',
          context_keys: ['discipline', 'ip_ownership_answer', 'catalog_inventory'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Make one licensing deal',
        what: 'Approach one potential licensee with a concrete proposal. Could be a brand, publisher, platform, sync agent, or retailer. Specific terms, specific timeline, specific rights granted (not all rights — specific, limited rights).',
        why: 'One deal proves the model. It generates evidence that your catalog has commercial value, which makes every subsequent deal easier.',
        how: 'Attorney review recommended for first licensing agreement. In Sequence provides referrals.',
        timeline: '4-6 weeks',
        done_signal: 'Signed licensing agreement with defined terms and payment schedule.',
      },
    ],
    structures: [27, 28, 31],
    case_studies: [],
  },

  // ── 06: The High-Earner Without Ownership ────────────────────────
  {
    id: 'high_earner_no_ownership',
    name: 'The High-Earner Without Ownership',
    description: 'Stage 2 (high-end) to 3. Significant income but no ownership positions. Structural gaps costing real money.',
    stage_range: [2, 3.5],
    creative_modes: ['maker', 'service', 'hybrid', 'performer', 'builder', 'transition'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Fix the structural gap',
        what: 'If sole prop or basic LLC earning $250K+, address entity structure and tax optimization immediately. Meet with a creative-industry CPA about S-Corp election, entity restructuring, and tax strategy.',
        why: 'At your income level, structural misalignment costs $15K-$50K+ annually in tax inefficiency alone — plus you lack the entity structure to hold equity if an opportunity arises.',
        how: 'In Sequence referrals to creative-industry CPAs and attorneys.',
        timeline: 'Consultation within 2 weeks. Implementation within 6 weeks.',
        done_signal: 'Tax-optimized entity structure in place.',
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Convert one relationship to ownership',
        what: "Identify your longest-standing, highest-trust professional relationship where you've contributed significant value. Propose restructuring the engagement to include equity, profit participation, or revenue share alongside (or instead of) fees.",
        why: "You have relationships where you've generated enormous value and captured none of the ownership. One conversion changes how you think about every relationship that follows.",
        how: 'In Sequence Structures #3 (Project Equity), #17 (Equity-for-Services), #24 (Revenue Share Partnership). The AI assistant can help you draft the proposal and model the terms.',
        timeline: 'Identify within 1 week. Draft proposal within 3 weeks. Conversation within 5 weeks.',
        done_signal: "You've had the ownership conversation with one key relationship.",
        ai_assist: {
          prompt_template: 'Help me draft an equity/ownership proposal for [relationship description]. Current engagement is [describe]. I want to propose [general direction].',
          context_keys: ['discipline', 'income_range', 'income_structure', 'what_they_pay_for', 'demand_level'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Start tracking your value creation',
        what: "For the next 90 days, document the value you create in every significant engagement. Not just deliverables — business outcomes, revenue generated, opportunities created, decisions influenced.",
        why: "Ownership conversations require evidence. When you can say \"my direction on your brand contributed to X% revenue growth,\" you're not asking for equity — you're demonstrating why it's appropriate.",
        how: 'Simple log: Engagement | What I Did | Business Impact (estimated) | Date.',
        timeline: 'Start immediately, review at 90 days',
        done_signal: '90-day value creation log exists and can be referenced in future negotiations.',
      },
    ],
    structures: [3, 17, 24],
    case_studies: [],
  },

  // ── 07: The Capital Allocator ────────────────────────────────────
  {
    id: 'capital_allocator',
    name: 'The Capital Allocator',
    description: 'Stage 3.5–4. Revenue compounding, multiple assets in play. Shifting from operator to portfolio role — allocating capital, governance, and judgment rather than executing.',
    stage_range: [3, 4],
    creative_modes: ['builder', 'service', 'transition'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Formalize the allocator role',
        what: 'Decide the legal structure for your capital: family office, investment LLC, friends+family fund, or a holding company whose mandate is to invest rather than operate. Each has different tax treatment, reporting requirements, and LP/investor eligibility rules.',
        why: "The jump from 'wealthy operator' to 'allocator' only compounds when there's a structure designed for allocation. Running investment activity through your operating LLC creates tax inefficiency, co-mingled liability, and a muddled identity — you end up neither a great operator nor a great investor.",
        how: 'Attorney with fund formation experience + CPA who works with family offices. In Sequence can refer. Expect 6–12 weeks to stand up cleanly. For a sub-$10M annual allocation, an investment LLC is often sufficient; above that, family office territory.',
        timeline: '6–12 weeks',
        done_signal: 'Entity structure is filed, bank accounts funded, initial investment policy statement drafted.',
        providers: [],
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Write your investment thesis',
        what: "A 1–2 page document that says what you will invest in, what you won't, what your expected hold period is, what check size you'll write, and what you bring besides capital (creative judgment, industry access, brand). The thesis is the filter.",
        why: "At Stage 4, every good pitch feels investable because you can afford it. That's the trap. A written thesis lets you say no fast and without ambiguity, and makes the yeses legible to co-investors, operators, and your own team.",
        how: 'The In Sequence AI assistant can help you draft this with your context. Focus on: thesis statement, sector fit, stage, check size, terms you want (pro rata, board observer, info rights), and deal types you avoid.',
        timeline: '2–4 weeks',
        done_signal: 'Written thesis exists and is shared with your advisor / CPA / attorney so they can filter inbound.',
        ai_assist: {
          prompt_template: 'Help me draft an investment thesis for my family office / investment LLC. I am investing in [sectors], at [stage], and I bring [value beyond capital].',
          context_keys: ['discipline', 'income_range', 'equity_positions', 'creative_mode'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Make your first structured portfolio bet',
        what: 'Write a check — or convert existing informal support — using formal terms: signed term sheet, defined equity percentage, vesting (if operator involvement is expected), pro-rata rights, information rights, and a monitoring cadence (quarterly updates minimum).',
        why: "One structured deal sets the precedent for every follow-on. Informal 'friend checks' look generous but create awkward governance — you can't exit, you can't reprice, you can't add-on cleanly. Formal deals compound into a portfolio; informal ones compound into complaints.",
        how: 'Structure #17 (Equity-for-Services) if you are also contributing expertise. Structure #19 (Vesting Equity) for operator stakes. Structure #32 (Royalty/Equity Hybrid) for IP-adjacent deals. Attorney review is mandatory here — not optional.',
        timeline: '4–8 weeks from thesis to signed terms',
        done_signal: 'First deal is closed on written terms with quarterly reporting established.',
      },
    ],
    structures: [9, 17, 19, 21, 32],
    case_studies: [],
  },

  // ── 08: The Creative Principal ───────────────────────────────────
  {
    id: 'creative_principal',
    name: 'The Creative Principal',
    description: 'Stage 3–4. Taste is the product across multiple ventures. Each division, label, or line depends on your creative direction — the leverage is your vision, replicated through systems and teams.',
    stage_range: [3, 4],
    creative_modes: ['maker', 'performer', 'hybrid'],
    required_flags: [],
    excluded_flags: [],
    actions: [
      {
        order: 1,
        type: 'foundation',
        title: 'Build the creative services holding structure',
        what: 'A parent entity holds your core IP and creative-director services contract. Operating divisions (fashion, music, products, film, etc.) are subsidiary LLCs that license the core IP and retain you as creative director. This replaces the informal "my name is on everything" arrangement with actual structure.',
        why: "Without this structure, every venture's goodwill and IP sit exposed inside its operating LLC — so an underperforming division can drag down assets you want to protect, and selling one division accidentally transfers the vibe that fuels the others. Creative-services holding isolates each bet, taxes them efficiently, and makes succession possible.",
        how: 'This is a multi-attorney project: entity formation + IP transfer agreements + inter-company licensing + creative-services master agreement. In Sequence provides referrals. 3–6 month buildout, phased across existing ventures.',
        timeline: '3–6 months',
        done_signal: 'Holding entity is filed, primary IP assigned to it, one division is operating under the new licensing structure.',
        providers: [],
      },
      {
        order: 2,
        type: 'positioning',
        title: 'Codify the taste',
        what: "Write the creative principles, standards, and decision-making frameworks that travel when you're not in the room. This is not a brand guide — it's an operating doctrine: what you'd approve, what you'd kill, and the specific questions that separate the two.",
        why: "At Stage 3–4 your bandwidth becomes the single point of failure. Either you codify your taste in artifacts your team can use — or every decision routes through you forever and the organization can't scale past your calendar. The ventures that survive the principal's absence (Abloh → Off-White / ICA; Rubin → American Recordings) had written taste. The ones that don't, didn't.",
        how: 'Draft: 5–10 principles, 3–5 worked examples of "approved vs rejected", a single page decision framework. The AI assistant can interview you to extract this. Review annually with the team.',
        timeline: '4–8 weeks',
        done_signal: 'Doctrine document exists, has been workshopped with your senior creative leads, and is cited in at least one real creative decision.',
        ai_assist: {
          prompt_template: 'Help me codify my creative taste as a written doctrine. My work spans [disciplines]. The decisions I keep making that separate good from bad work are [examples].',
          context_keys: ['discipline', 'creative_mode', 'sub_discipline'],
        },
      },
      {
        order: 3,
        type: 'momentum',
        title: 'Hire or partner with a second principal',
        what: 'Someone with genuine creative authority (not just execution ability) who can run one or more divisions with final-call power, bounded by the written doctrine. This is a principal-level hire or a co-founder-class partner — not a COO and not a senior creative.',
        why: "The doctrine is inert without a second mind trusted to apply it. Stage 4 creative principals who don't make this move plateau at the ceiling of their calendar; the ones who do (Abloh + Alex Wolfgang at OW; Rubin + Schnapf at AR) unlock genuine parallel output.",
        how: 'Structure #18 (Founder / Co-Founder Equity) or Structure #20 (Performance Equity) for the partnership terms. Equity + creative-director title + defined authority boundaries. Attorney-drafted founders agreement.',
        timeline: 'Identify within 1–2 quarters; close within 6 months',
        done_signal: 'Second principal is operating with decision authority in at least one division, using the doctrine.',
      },
    ],
    structures: [9, 12, 18, 20, 27, 28, 31, 33, 35],
    case_studies: [],
  },
];

/** Look up an archetype by ID */
export function getArchetypeById(id: string): Archetype | undefined {
  return ARCHETYPES.find(a => a.id === id);
}
