// This file will be auto-generated by Supabase CLI:
// npx supabase gen types typescript --project-id zpgbdxuwgoqfsbqscqrc > src/types/database.ts
//
// For now, we define minimal types manually.

export type Profile = {
  id: string;
  full_name: string | null;
  email: string | null;
  avatar_url: string | null;
  role: "member" | "admin";
  status: "active" | "inactive" | "suspended";
  onboarding_completed: boolean;
  // Extended fields (from 00002 migration)
  bio: string | null;
  disciplines: string[];
  career_stage: string | null;
  income_range: string | null;
  interests: string[];
  // Assessment-ready (populated by Phase 2)
  creative_mode: string | null;
  detected_stage: 1 | 2 | 3 | 4 | null;
  archetype_primary: string | null;
  assessment_completed_at: string | null;
  // Timestamps
  created_at: string;
  updated_at: string;
};

export type Subscription = {
  id: string;
  user_id: string;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  stripe_price_id: string | null;
  plan: "annual" | "student" | "library" | "full_access" | "coaching";
  status: "active" | "past_due" | "canceled" | "trialing" | "incomplete";
  current_period_start: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  created_at: string;
  updated_at: string;
};

// Re-export assessment types for convenience
export type {
  Assessment,
  StrategicPlan,
  AssessmentAction,
  StrategicRoadmap,
} from './assessment';

export type LibraryContent = {
  id: string;
  type: "structure" | "case_study" | "article" | "guide";
  title: string;
  slug: string;
  description: string | null;
  content: Record<string, unknown> | null;
  cover_image_url: string | null;
  tags: string[];
  access_level: "public" | "member" | "admin";
  published: boolean;
  published_at: string | null;
  author: string | null;
  read_time_minutes: number | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
};
